TDE_OBJS = \
 	src/access/pg_tde_tdemap.o \
 	src/access/pg_tde_xlog_encrypt.o \
 	src/catalog/tde_global_space.o \
 	src/catalog/tde_keyring.o \
 	src/catalog/tde_keyring_parse_opts.o \
 	src/catalog/tde_principal_key.o \
 	src/common/pg_tde_utils.o \
 	src/encryption/enc_aes.o \
 	src/encryption/enc_tde.o \
 	src/keyring/keyring_api.o \
 	src/keyring/keyring_curl.o \
 	src/keyring/keyring_file.o \
 	src/keyring/keyring_vault.o