#include "postgres_fe.h"

#include "pg_tde_fe.h"
#include "common/pg_tde_utils.h"
#include "encryption/enc_aes.h"
#include "keyring/keyring_file.h"
#include "keyring/keyring_vault.h"
#include "keyring/keyring_kmip.h"

/* Frontend has to call this to access keys */
void
pg_tde_fe_init(const char *kring_dir)
{
	AesInit();
	InstallFileKeyring();
	InstallVaultV2Keyring();
	InstallKmipKeyring();
	pg_tde_set_data_dir(kring_dir);
}

#if PG_VERSION_NUM < 170000

/*
 * Before PostgreSQL 17 the JSON error message were only avilable to backend
 * code so this is code taken from PostgreSQL 16.14 with minimal modifications.
 */

#include "common/jsonapi.h"

/*
 * Extract the current token from a lexing context, for error reporting.
 */
static char *
extract_token(JsonLexContext *lex)
{
	int			toklen = lex->token_terminator - lex->token_start;
	char	   *token = palloc(toklen + 1);

	memcpy(token, lex->token_start, toklen);
	token[toklen] = '\0';
	return token;
}

/*
 * Construct an (already translated) detail message for a JSON error.
 *
 * Note that the error message generated by this routine may not be
 * palloc'd, making it unsafe for frontend code as there is no way to
 * know if this can be safely pfree'd or not.
 */
char *
json_errdetail(JsonParseErrorType error, JsonLexContext *lex)
{
	switch (error)
	{
		case JSON_SUCCESS:
			/* fall through to the error code after switch */
			break;
		case JSON_ESCAPING_INVALID:
			return psprintf(_("Escape sequence \"\\%s\" is invalid."),
							extract_token(lex));
		case JSON_ESCAPING_REQUIRED:
			return psprintf(_("Character with value 0x%02x must be escaped."),
							(unsigned char) *(lex->token_terminator));
		case JSON_EXPECTED_END:
			return psprintf(_("Expected end of input, but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_ARRAY_FIRST:
			return psprintf(_("Expected array element or \"]\", but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_ARRAY_NEXT:
			return psprintf(_("Expected \",\" or \"]\", but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_COLON:
			return psprintf(_("Expected \":\", but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_JSON:
			return psprintf(_("Expected JSON value, but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_MORE:
			return _("The input string ended unexpectedly.");
		case JSON_EXPECTED_OBJECT_FIRST:
			return psprintf(_("Expected string or \"}\", but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_OBJECT_NEXT:
			return psprintf(_("Expected \",\" or \"}\", but found \"%s\"."),
							extract_token(lex));
		case JSON_EXPECTED_STRING:
			return psprintf(_("Expected string, but found \"%s\"."),
							extract_token(lex));
		case JSON_INVALID_TOKEN:
			return psprintf(_("Token \"%s\" is invalid."),
							extract_token(lex));
		case JSON_UNICODE_CODE_POINT_ZERO:
			return _("\\u0000 cannot be converted to text.");
		case JSON_UNICODE_ESCAPE_FORMAT:
			return _("\"\\u\" must be followed by four hexadecimal digits.");
		case JSON_UNICODE_HIGH_ESCAPE:
			/* note: this case is only reachable in frontend not backend */
			return _("Unicode escape values cannot be used for code point values above 007F when the encoding is not UTF8.");
		case JSON_UNICODE_UNTRANSLATABLE:
			/* note: this case is only reacable in backend code */
			Assert(false);
		case JSON_UNICODE_HIGH_SURROGATE:
			return _("Unicode high surrogate must not follow a high surrogate.");
		case JSON_UNICODE_LOW_SURROGATE:
			return _("Unicode low surrogate must follow a high surrogate.");
		case JSON_SEM_ACTION_FAILED:
			/* fall through to the error code after switch */
			break;
	}

	/*
	 * We don't use a default: case, so that the compiler will warn about
	 * unhandled enum values.  But this needs to be here anyway to cover the
	 * possibility of an incorrect input.
	 */
	elog(ERROR, "unexpected json parse error type: %d", (int) error);
	return NULL;
}

#endif
