# MkDocs general configuration

site_name: Percona Transparent Data Encryption for PostgreSQL
site_description: Documentation
site_author: Percona LLC
copyright: >
  <a href="https://www.percona.com/about">Percona LLC</a> and/or its affiliates © 2025 — <a href="#__consent">Cookie Consent</a>

repo_name: percona/postgres
repo_url: https://github.com/percona/postgres
edit_uri: edit/TDE_REL_17_STABLE/contrib/pg_tde/documentation/docs

use_directory_urls: false

# Theme settings
theme:
  name: material
  logo: _images/postgresql-mark.svg
  favicon: _images/postgresql-fav.svg
  custom_dir: _resourcepdf/overrides
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Color theme set to Automatic. Click to change
    - media: "(prefers-color-scheme: light)"
      scheme: percona-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Color theme set to Light Mode. Click to change
    - media: "(prefers-color-scheme: dark)"
      scheme: percona-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Color theme set to Dark Mode. Click to change

# Theme features

  features:
    - search.share
    - search.highlight
    - content.code.copy
    - content.action.view
#    - content.action.edit
    - content.tabs.link
    - navigation.top
    - navigation.tracking
    - navigation.indexes

extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  - css/percona.css
  - css/design.css
  - css/osano.css
  - css/postgresql.css
  - css/landing.css

extra_javascript:
  - js/version-select.js
  - js/promptremover.js
  - js/consent.js

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
  - admonition
  - md_in_html
  - footnotes
  - def_list   # https://michelf.ca/projects/php-markdown/extra/#def-list
  - meta
  - smarty:
      smart_angled_quotes: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      linenums: false
  - pymdownx.snippets:
      base_path: ["snippets"]
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
         - _resource/.icons

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - open-in-new-tab:
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
  - section-index # Adds links to nodes - comment out when creating PDF
#  - htmlproofer # Uncomment to check links - but extends build time significantly
  - glightbox
  - macros:
      include_yaml:
        - 'variables.yml' # Use in markdown as '{{ VAR }}'
  - print-site:
      add_to_navigation: false
      print_page_title: 'Percona Transparent Data Encryption documentation'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 2
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_headings_depth: 1
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "docs/templates/pdf_cover_page.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-J4J70BNH0G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Want to improve this page? Click  <strong>Edit this page on GitHub</strong> above to submit a pull request.

nav:
  - "Home": index.md
  - get-help.md
  - "Features": features.md 
  - "Overview":
    - "About Transparent Data Encryption": index/about-tde.md
    - "About pg_tde": 
      - "Benefits of pg_tde": index/how-tde-helps.md
      - "How pg_tde works": index/how-does-tde-work.md
      - "Encrypted data scope": index/tde-encrypts.md
      - "Table access methods and pg_tde": index/table-access-method.md
    - "Limitations of pg_tde": index/tde-limitations.md
    - "Versions and supported PostgreSQL deployments": index/supported-versions.md
  - "Get started":
    - "1. Install pg_tde": install.md
    - "1.1 Via apt": apt.md
    - "1.2 Via yum": yum.md   
    - "2. Configure pg_tde": setup.md
    - "2.1 Configure Key Management (KMS)": 
      - "Key management overview": global-key-provider-configuration/overview.md
      - "KMIP configuration": global-key-provider-configuration/kmip-server.md
      - "Fortanix configuration": global-key-provider-configuration/kmip-fortanix.md  
      - "Vault configuration": global-key-provider-configuration/vault.md
      - "Thales configuration": global-key-provider-configuration/kmip-thales.md
      - "Using OpenBao as a key provider": global-key-provider-configuration/kmip-openbao.md
      - "Keyring file configuration": global-key-provider-configuration/keyring.md
    - "2.2 Global Principal Key configuration": global-key-provider-configuration/set-principal-key.md
    - "3. Validate encryption with pg_tde": test.md
    - "4. Configure WAL encryption": wal-encryption.md
  - "Technical reference":
    - "Overview": advanced-topics/tech-reference.md
    - "Architecture": architecture/architecture.md
    - "GUC variables": variables.md
    - "Functions": functions.md
    - "Streaming Replication with tde_heap": replication.md
  - "TDE operations":
    - "pg_tde CLI tools":
      - "Overview": command-line-tools/cli-tools.md
      - "pg_tde_change_key_provider": command-line-tools/pg-tde-change-key-provider.md
      - "pg_tde_archive_decrypt": command-line-tools/pg-tde-archive-decrypt.md
      - "pg_tde_restore_encrypt": command-line-tools/pg-tde-restore-encrypt.md
      - "pg_checksums": command-line-tools/pg-tde-checksums.md 
      - "pg_waldump": command-line-tools/pg-waldump.md
    - "Uninstall pg_tde": how-to/uninstall.md
    - "Configure Multi-tenancy": how-to/multi-tenant-setup.md
    - "Encryption Enforcement": how-to/enforcement.md
    - "Decrypt an Encrypted Table": how-to/decrypt.md
    - "Backup with WAL encryption enabled": how-to/backup-wal-enabled.md
    - "Restore an encrypted pg_tde backup": how-to/restore-backups.md
  - faq.md
  - "Release notes":
    - "Release notes index": release-notes/release-notes.md
    - "2.0": release-notes/release-notes-v2.0.md
    - "1.0": release-notes/release-notes-v1.0.md
    - "Release Candidate 2": release-notes/rc2.md
    - "Release Candidate 1": release-notes/rc.md
    - "2024 (Alpha 1 - Beta 2)":
      - "Beta 2": release-notes/beta2.md
      - "Beta": release-notes/beta.md
      - "Alpha 1": release-notes/alpha1.md
    - "2023 (MVP)":
      - "MVP": release-notes/mvp.md
  - contribute.md
