name: Code coverage
on:
  pull_request:
    paths-ignore:
      - contrib/pg_tde/documentation/**
  push:
    branches:
      - TDE_REL_17_STABLE
    paths-ignore:
      - contrib/pg_tde/documentation/**

env:
  # Avoid failures on slow recovery
  PGCTLTIMEOUT: 120
  PG_TEST_TIMEOUT_DEFAULT: 300

jobs:
  collect:
    name: Collect and upload
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # KMIP server doesn't support Python 3.12 for now: https://github.com/OpenKMIP/PyKMIP/pull/707
      - name: Downgrade python to 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: ci_scripts/ubuntu-deps.sh

      - name: Build postgres
        run: ci_scripts/make-build.sh debug --enable-coverage

      - name: Setup kmip and vault
        run: ci_scripts/setup-keyring-servers.sh

      - name: Test postgres with TDE to generate coverage
        run: ci_scripts/make-test.sh tde

      - name: Collect coverage data
        run: find . -type f -name "*.c" ! -path '*libkmip*' | xargs -t gcov -abcfu
        working-directory: contrib/pg_tde

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: contrib/pg_tde
          files: "*.c.gcov"

      - name: Report on test fail
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: coverage-testlog-tde
          path: |
            build/testrun
            contrib/*/log
            contrib/*/regression.diffs
            contrib/*/regression.out
            contrib/*/results
            contrib/*/tmp_check
            contrib/*/t/results
            src/test/*/log
            src/test/*/regression.diffs
            src/test/*/regression.out
            src/test/*/results
            src/test/*/tmp_check
          retention-days: 3
