name: Docs
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "documentation/**"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/documentation

    steps:
      - name: Chekout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.x"

      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Deploy
        run: |
          mike set-default main -p
          mike retitle main "Beta" -p
          mike deploy main -p
