name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main
      - release-[0-9]+.[0-9]+*
      - debug-macos
    paths-ignore:
      - documentation/**

jobs:
  macos:
    name: MacOS matrix
    strategy:
      fail-fast: false
      matrix:
        pg_version: [18]
        os: [macos-15]
        compiler: [clang]
        build_type: [debugoptimized]
    uses: ./.github/workflows/build-and-test.yml
    with:
        pg_version: ${{ matrix.pg_version }}
        os: ${{ matrix.os }}
        compiler: ${{ matrix.compiler }}
        build_type: ${{ matrix.build_type }}
    secrets: inherit
