name: Format
on:
  pull_request:
    paths-ignore:
      - contrib/pg_tde/documentation/**
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: ci_scripts/ubuntu-deps.sh

      - name: Build postgres
        run: ci_scripts/make-build.sh debug

      - name: Update typedefs
        run: ci_scripts/dump-typedefs.sh

      - name: Run pgindent
        run: ci_scripts/run-pgindent.sh --check --diff

      - name: Run pgperltidy
        run: ci_scripts/run-pgperltidy.sh --assert-tidy --standard-error-output
