name: Format
on:
  pull_request:
    paths-ignore:
      - documentation/**
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          path: 'src'
          submodules: recursive

      - name: Clone postgres repository
        uses: actions/checkout@v5
        with:
          path: 'postgres'
          repository: 'percona/postgres.git'
          ref: 'PSP_REL_17_STABLE'

      - name: Install dependencies
        run: src/ci_scripts/ubuntu-deps.sh

      - name: Build postgres
        run: src/ci_scripts/build-and-install-psp.sh debug

      - name: Build pg_tde
        run: src/ci_scripts/make-build.sh debug

      - name: Update typedefs
        run: src/ci_scripts/dump-typedefs.sh

      - name: Run pgindent
        run: src/ci_scripts/run-pgindent.sh --check --diff

      - name: Run pgperltidy
        run: src/ci_scripts/run-pgperltidy.sh --assert-tidy --standard-error-output
