name: postgresql-16-src-meson-macos
on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    name: pg-16-src-meson-test
    runs-on: macos-14
    steps:
      - name: Install dependencies
        run: |
          brew tap hashicorp/tap
          brew install meson gnu-sed icu4c hashicorp/tap/vault
          sudo /usr/bin/perl -MCPAN -e 'install HTTP::Server::Simple'
          sudo /usr/bin/perl -MCPAN -e 'install IPC::Run'
          sudo /usr/bin/perl -MCPAN -e 'install Text::Trim'

      - name: Clone postgres repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'postgres/postgres'
          ref: 'a81e5516fa4bc53e332cb35eefe231147c0e1749'
          path: 'src'

      - name: Clone pg_tde repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: 'src/contrib/pg_tde'

      - name: Include pg_tde in meson build
        run: |
          echo "subdir('pg_tde')" >> src/contrib/meson.build

      - name: Build postgres
        run: |
          export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig"
          meson setup build --prefix `pwd`/../inst --buildtype=debug -Dcassert=true
          cd build && ninja && ninja install
        working-directory: src

      - name: Test pg_tde
        run: |
          TV=$(mktemp)
          { exec >$TV; vault server -dev; } &
          sleep 10
          export ROOT_TOKEN=$(cat $TV | grep "Root Token" | cut -d ":" -f 2 | xargs echo -n)
          echo "Root token: $ROOT_TOKEN"
          meson test --suite setup -v
          meson test --suite pg_tde -v --num-processes 1
        working-directory: src/build

      - name: Report on test fail
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: ${{ failure() }}
        with:
          name: Regressions diff and postgresql log
          path: |
            src/build/testrun/pg_tde/regress/
          retention-days: 3

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env
          pwd
